language: node_js
node_js:
      - "node"
cache: yarn
script:
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then exp login -u $EXP_USERNAME -p $EXP_PASSWORD --non-interactive && exp publish; fi'
      - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi'
